apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patient-ingress
  annotations:
    # Disable SSL redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Enable use of regular expressions in path matching
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Rewrite the path to remove the "/api/Doctor/" prefix
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # Specify the ingress class name
  ingressClassName: nginx
  # Specify the rules for this ingress resource
  rules:

    - # Specify the host name for this rule
      http:
        paths:

          - # Specify the path to match for this rule
            path: /api/Patient/Add_Patient
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Patient/Update_Patient/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Patient/Get_all_Patient
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Patient/Get_by_ID/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Patient/PatientExist/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Patient/isExist/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80

          - # Specify the path to match for this rule
            path: /api/Patient/phoneNo/isExist/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80

          
          - # Specify the path to match for this rule
            path: /api/Prescription/AddPrescription
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Prescription/GetPrescriptionById/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/VisitDetails/AddVisitDetails
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/VisitDetails/GetVisitDetailsById/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/VisitDetails/GetVisitDetailsByAcceptanceId/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/VisitDetails/GetParticularVisitDetailsById/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Test/AddTest
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Test/GetTestListbyid/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Test/GetTestIdbyname/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Test/UpdateTest/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Test/DeleteTest/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
          - # Specify the path to match for this rule
            path: /api/Test/DeleteTest/?p*
            pathType: Prefix
            backend:
              service:
                # Specify the name of the backend service to forward requests to
                name: patient-api-service
                port:
                  # Specify the port number of the backend service to forward requests to
                  number: 80
  
  
  
  
  
  
